### ISSUE TITLE
Recipe Type: Throw Item into Fire

### ISSUE THREAD

**Issue by TheUntamed** [MaxNeedsSnacks/Interactio#10]
Tossing an item into fire transforms that item into something else.

**Comment by MaxNeedsSnacks** [comment]
Might be a little stupid to do for multiple items, so I might make it single-input only for now, but that also sounds like a good idea. I'll see what I can do!

**Comment by TheUntamed** [comment]
Thank you very much

**Comment by NielsPilgaard** [comment]
I might also use this recipetype, just fyi 😄

**Comment by dozingpip** [comment]
I tried to use this new recipe type like [this](https://pastebin.com/p4QKrxsD), and tried it with `inputs` changed to just `input` with a single input item, but the recipe doesn't take either way? I tried changing the type to `interactio:item_explode` and that worked fine. I was basing the `item_burning` type name on https://github.com/MaxNeedsSnacks/Interactio/blob/1cde45467d050c09d53e62cd0c69d2d0bd0b0d44/src/main/java/ky/someone/mods/interactio/recipe/base/InWorldRecipeType.java#L28  Is that not where I should be looking?

**Comment by MaxNeedsSnacks** [comment]
This release hasn't been pushed yet as I still need to do a lot of cleanup with that and have been pretty busy with uni work unfortunately, so item burning *currently* doesn't exist just yet :/

**Comment by ghost** [comment]
Has this been implemented yet? I understand you're busy just checking on progress. Would really like to use this in a modpack im working on.
