### ISSUE TITLE
Working in SP, but not on server

### ISSUE THREAD

**Issue by davqvist** [MaxNeedsSnacks/Interactio#12]
Interactio 2.0.1
Forge 31.1.63

recipe: https://pastebin.com/qSMUdm3S
Like in the title, transfered my pack to the server, but the transformation just doesn't work on a server while it worked before in SP.

**Comment by MaxNeedsSnacks** [comment]
That's odd, I would've hoped to have fixed client / server stuff by now. Lemme check out what it is again

**Comment by MaxNeedsSnacks** [comment]
Turns out I'd already fixed this long ago, I just never pushed the changes to master 🤦‍♂️. That should be solved in the next release, which I'll push out together with the Anvil Smashing recipe type today!

**Comment by MaxNeedsSnacks** [comment]
Version 2.0.2 should now be out on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/interactio/files/2948034) and hopefully fix this issue!
