### ISSUE TITLE
1.16.1 Crashing with forge 67+

### ISSUE THREAD

**Issue by Darkere** [MaxNeedsSnacks/Interactio#14]
In forge 67 forge had to move the command registration to a new RegisterCommandsEvent. 

Mods using the old FMLServerStartingEvent crash. 

https://gist.github.com/Darkere/422baf1a3cc6fdfa28199688e348752c

**Comment by MaxNeedsSnacks** [comment]
Good catch! I'll be sure to push a hotfix out asap!

**Comment by MaxNeedsSnacks** [comment]
New version's out on CurseForge now ^^
