### ISSUE TITLE
Console is spamming Infos

### ISSUE THREAD

**Issue by Fuggschen** [MaxNeedsSnacks/Interactio#16]
Hi,

we are running the Enigmatica 6 modpack on a dedicated server and at some random point (e.g. nobody is on the server or we are only standing afk at our base) the console is full of this info message: [https://pastebin.com/40dzgX6t](https://pastebin.com/40dzgX6t)
I got to this position "x=-306.55, y=73.00, z=97.47" but there is nothing. No fluid, no nether quartz, only air.
Last time I didn't noticed this and we got after our daily restart a 5gb logfile full of this messages.

Can you tell us what that means and how to fix it or to mute this?

**Comment by EntropyRiot** [comment]
Same here but where Fuggschen has a location, we are seeing an empty entry. Also running Enigmatic 6 here on a dedicated host and are seeing at the same output: https://pastebin.com/SgLLu0t9
Server restarted and error appeared to stop - users played and all was ok but then the error as seen in the above paste began spamming the log entries.

latest.log file had grown to excess of 70 GB.

**Comment by MaxNeedsSnacks** [comment]
This was an annoying debug line that I forgot to remove initially while working on 2.0.5, I already hotfixed it and the fixed version is out on CurseForge here:

https://www.curseforge.com/minecraft/mc-mods/interactio/files/3036266

You should be able to just drop-in replace the current version, which I'll probably actually be taking down completely to avoid more people having to go through this until Niller updates his pack
