### ISSUE TITLE
recipe in fluid still

### ISSUE THREAD

**Issue by AlleCraft-alterego** [MaxNeedsSnacks/Interactio#27]
you can add recipe in fluid still ? if put a block next fluid still or drop item in it.... 
exemple: put a block of cobblestone next water and in min X ticks and max ticks transform cobblestone in gravel, and like if drop cobblestone in water still

**Comment by MaxNeedsSnacks** [comment]
This somewhat ties in with #18 (recipe progress), but I'm not actually 100% sure on how to do this, at least not without the mod also having to be installed client-side
