### ISSUE TITLE
[1.16.3] Don`t setup mod

### ISSUE THREAD

**Issue by Rumaruka** [MaxNeedsSnacks/Interactio#28]
Minecraft: 1.16.3
Forge: 34.1.32
Mod Version: 3.0.0
Crash: https://pastebin.com/nJVXBrrY

**Comment by MaxNeedsSnacks** [comment]
Ah yes, Forge and their breaking changes again... I'll fix this tomorrow when I can find the time! ^^

**Comment by Rumaruka** [comment]
Oh , thank you :) 
Your mod - main mechanic in my modpack )

**Comment by MaxNeedsSnacks** [comment]
Sorry for the delay, the hotfix should be on CurseForge shortly!
