### ISSUE TITLE
Crash when loading on Dedicated Server

### ISSUE THREAD

**Issue by Nachtflame** [MaxNeedsSnacks/Interactio#3]
Hadn't had a chance to get it onto a server yet.  Wish I had before updating my pack[+server pack] today. :/

Forge 28.2.1
Interactio 1.2.1
MC 1.14.4

Getting the following:

```[18:57:51] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Interactio (interactio) encountered an error during the common_setup event phase
§7Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}

**Comment by MaxNeedsSnacks** [comment]
oh dear that REALLY shouldn't happen, actually... hrm
lemme figure out what's wrong

**Comment by MaxNeedsSnacks** [comment]
Okay so it has to do with https://github.com/MaxNeedsSnacks/Interactio/blob/master/src/main/java/dev/maxneedssnacks/interactio/network/PacketCraftingParticle.java, obviously, as that's the only thing that happens during common setup.

The thing is, any stuff that's client-side ONLY **should** error in a different way anyways if for some reason it were to be executed serverside, so idk why it's deciding to run it here

**Comment by MaxNeedsSnacks** [comment]
Just pushed a new commit https://github.com/MaxNeedsSnacks/Interactio/commit/7780cdb0da4a3cb477687d676abbef4dae18a53a that probably fixes your issue, can you try whether it works with the jar from that commit? (should be under artifacts if you click on the tick and then "details")

**Comment by MaxNeedsSnacks** [comment]
Just pushed a new commit https://github.com/MaxNeedsSnacks/Interactio/commit/7780cdb0da4a3cb477687d676abbef4dae18a53a that probably fixes your issue, can you try whether it works with the jar from that commit? You might need to update it on both client and server, but if this works, I'll be sure to push a fix out to Curseforge by tomorrow! (check the "build" file [here](https://github.com/MaxNeedsSnacks/Interactio/actions/runs/40950522))

**Comment by MaxNeedsSnacks** [comment]
Seems to work perfectly fine in userdev and my test instance now, so I hope that simple fix resolved it. I've decided to push this to Curseforge already, so feel free to get the updated version directly from [here](https://www.curseforge.com/minecraft/mc-mods/interactio/files/2883974) instead of using that manually built one.

Anyways, if this didn't fix your issue, feel free to add more to this issue, I won't close it just yet until everything works out for you as well ^^

**Comment by Nachtflame** [comment]
Looks good!  No issues loading this time.  Thank you for the prompt response/fix!

**Comment by MaxNeedsSnacks** [comment]
No worries, should anything come up again, feel free to reopen this or get in touch with me otherwise ^^
