### ISSUE TITLE
crash with new update

### ISSUE THREAD

**Issue by AlleCraft-alterego** [MaxNeedsSnacks/Interactio#30]
[latest.log](https://github.com/MaxNeedsSnacks/Interactio/files/5464780/latest.log)

**Comment by MaxNeedsSnacks** [comment]
Found the problem, god damnit
https://github.com/MaxNeedsSnacks/Interactio/blob/ea8614a75eb25f52f3e1e53d99b554f58e3b70d8/src/main/java/dev/maxneedssnacks/interactio/core/mixin/RecipeManagerMixin.java#L27

**Comment by AlleCraft-alterego** [comment]
very fast ^^
