### ISSUE TITLE
add 1.16.4 to approved minecraft version on curse

### ISSUE THREAD

**Issue by benbenlaw** [MaxNeedsSnacks/Interactio#31]
can you please add 1.16.4 to compatibal version please

**Comment by MaxNeedsSnacks** [comment]
Should be done! Please tell me if there's any issues with the mod on 1.16.4; still busy, but I'll try my best to solve them!

**Comment by benbenlaw** [comment]
thanks buddy nah mods great i use it for my modpack havent experianced any issues with it
