### ISSUE TITLE
fix annoying logs

### ISSUE THREAD

**Issue by Darkere** [MaxNeedsSnacks/Interactio#32]
There is now a way to sync Command args. Please do so :)
```Could not serialize dev.maxneedssnacks.interactio.command.CommandRegistryDump$RegistryArgument@7e8e968b (class dev.maxneedssnacks.interactio.command.CommandRegistryDump$RegistryArgument) - will not be sent to client!```

**Comment by MaxNeedsSnacks** [comment]
Sorry, I've been dealing with some personal stuff lately so I haven't had time to update this, but I'll be sure to push out a fix asap ^^
