### ISSUE TITLE
changing the consume fluid value does not make fluid get consumed

### ISSUE THREAD

**Issue by benbenlaw** [MaxNeedsSnacks/Interactio#35]
changing consume fluid value from 0 to 1 doesnt not make fluid ever get consumed

**Comment by MaxNeedsSnacks** [comment]
That doesn't seem right... I'll check it out when I get the time!

**Comment by benbenlaw** [comment]
Yeh not a problem for me lol but i feel like its not your intention haga

**Comment by MaxNeedsSnacks** [comment]
Do you mind sending me the recipe JSON that's failing real quick?

**Comment by benbenlaw** [comment]
I will send in the morning

**Comment by benbenlaw** [comment]
{
  "type": "interactio:item_fluid_transform",
  "inputs": [
    {
      "item": "rats:cheese",
      "count": 64,
      "return_chance": 0
    },
    {
      "item": "rats:cheese",
      "count": 64,
      "return_chance": 0
    },
    {
      "item": "rats:cheese",
      "count": 64,
      "return_chance": 0
    },
    {
      "item": "rats:cheese",
      "count": 64,
      "return_chance": 0
    }
  ],
  "fluid": {
    "fluid": "kubejs:weak_enriching_fluid"
  },
  "output": {
    "item": "rats:creative_cheese",
    "count": 1
    }
  },
  "consume_fluid": 1
}

**Comment by MaxNeedsSnacks** [comment]
The JSON you posted here is incorrect:
```jsonc
{
	"type": "interactio:item_fluid_transform",
	"inputs": [{
			"item": "rats:cheese",
			"count": 64,
			"return_chance": 0
		},
		{
			"item": "rats:cheese",
			"count": 64,
			"return_chance": 0
		},
		{
			"item": "rats:cheese",
			"count": 64,
			"return_chance": 0
		},
		{
			"item": "rats:cheese",
			"count": 64,
			"return_chance": 0
		}
	],
	"fluid": {
		"fluid": "kubejs:weak_enriching_fluid"
	},
	"output": {
		"item": "rats:creative_cheese",
		"count": 1
	} // <- this bracket shouldn't exist
        },
        "consume_fluid": 1
}
```

Can you see if it works if you fix the typo?

**Comment by benbenlaw** [comment]
yeah that works sorry haha

**Comment by MaxNeedsSnacks** [comment]
No worries, feel free to reopen if anything else comes up!

**Comment by benbenlaw** [comment]
do you have discord ?
