### ISSUE TITLE
Summon Entites

### ISSUE THREAD

**Issue by benbenlaw** [MaxNeedsSnacks/Interactio#36]
Not a bug just wondering if its possible to have a feature that would allow entites to be summoned

**Comment by benbenlaw** [comment]
any progress on this?

**Comment by MaxNeedsSnacks** [comment]
Nope, unfortunately not, I'm currently *pretty* busy with uni and other projects unfortunately, so I'm mostly just fixing bugs on this for now

**Comment by benbenlaw** [comment]
Thanks for replying i understand still love this mod
