### ISSUE TITLE
Ceramics Clay Buckets

### ISSUE THREAD

**Issue by benbenlaw** [MaxNeedsSnacks/Interactio#38]
so i have made a recipe which uses a empty clay bucket thrown into water to make a filled water bucket, however the recipe acepts any filled bucket

{
  "type": "interactio:item_fluid_transform",
  "inputs": [
    {
      "item":  "ceramics:clay_bucket",
      "count": 1
	}
  ],
  "fluid": {
    "fluid": "minecraft:water"
  },
  "output": {
    "item": "ceramics:clay_bucket",
    "count": 1,
    "nbt": {
      "fluid": "minecraft:water"
    }
  },
  "consume_fluid": 0
}

**Comment by MaxNeedsSnacks** [comment]
Clay buckets store the fluid they contain in their NBT data as you've already noticed. By default, Ingredients ignore NBT data when checking for inputs. To make them respect it explicitly, use

```jsonc
{
  "type": "forge:nbt", // custom ingredient type, only works on forge
  "item": "ceramics:clay_bucket",
  "count": 1,
  "nbt": ""
}
```

**Comment by benbenlaw** [comment]
this does not work

**Comment by MaxNeedsSnacks** [comment]
To be 100% clear, you need to use that **inside** the ingredient tag, so

```jsonc
{
  "ingredient": {
    "type": "forge:nbt", // custom ingredient type, only works on forge
    "item": "ceramics:clay_bucket",
    "count": 1,
    "nbt": ""
  }
}
```
