### ISSUE TITLE
Game Stage integration... is possible ?

### ISSUE THREAD

**Issue by AlleCraft-alterego** [MaxNeedsSnacks/Interactio#40]
Game Stage integration... is possible with datapack recipe ?

**Comment by MaxNeedsSnacks** [comment]
It's *possible* for me to do **some** integration with Game Stages, but you'll need to consider a LOT of side effects (for instance, what if a Dispenser drops items into the world, how would we track players placing fluids, Creeper explosions and so on)

**Comment by AlleCraft-alterego** [comment]
obviously it will be something to use carefully but it would be very useful
