### ISSUE TITLE
chore: Rework JEI Integration

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [MaxNeedsSnacks/Interactio#45]
Needs to support the new event system, and I kind of want to move away from the weird radial design we have currently

**Comment by MuteTiefling** [comment]
Suggestion for this: Could you put some placeholder items in that act as the 'machine' for display purposes? This way you could look up all recipes for a given mechanic by looking up the uses on that item.

**Comment by MaxNeedsSnacks** [comment]
I'm not entirely sure what to add as catalysts for fluid transforms and lightning channeling, to be honest haha

Empty buckets and a Trident maybe?

**Comment by MuteTiefling** [comment]
Sounds good to me :D
