### ISSUE TITLE
Add multiple weighted / chance outputs to recipes

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [MaxNeedsSnacks/Interactio#5]
This originally stems from a comment on CurseForge. The concrete plan would be to:

- [x] ~~Implement a `ChanceItemStack` class that associates possible outputs with different chances to spawn.~~
- [x] ~~Change the outputs of most recipe types to `List<ChanceItemStack>`~~
- [x] ~~Overhaul JEI integration such that it can represent multiple inputs -> multiple outputs without looking cluttered.~~

- [x] ~~*(Maybe) implement something for chances over 100% such that 195% for example could mean: 100% chance to spawn one set, 95% to spawn another*~~

EDIT: I took a slightly different approach when implementing this, instead of *chances* item outputs now have different weights to be picked as a random output. Recipes can have multiple rolls and also support "empty" weights, which return nothing if picked. I did introduce return chances to recipe inputs, though, which is now 0% by default for **all** recipes.

**Comment by Partonetrain** [comment]
Hey, I'm the one who suggested this. If it helps at all, here's an example of the Create mod doing the same thing:

https://github.com/Creators-of-Create/Create/blob/0.2/src/main/java/com/simibubi/create/modules/contraptions/processing/ProcessingRecipe.java
https://github.com/Creators-of-Create/Create/blob/0.2/src/main/java/com/simibubi/create/modules/contraptions/processing/ProcessingRecipeSerializer.java

And the actual recipe type, as all of Create recipes extend ProcessingRecipe:
https://github.com/Creators-of-Create/Create/blob/0.2/src/main/java/com/simibubi/create/modules/contraptions/components/crusher/CrushingRecipe.java

Anyway thanks for taking my suggestion!

**Comment by MaxNeedsSnacks** [comment]
No worries, I also came up with another idea while going through create - input return chances / consume chances per input, so you can have a recipe that for example uses 5 gunpowder, but has a 20% chance to return them, so on average you get 1 gunpowder back.

**Comment by MaxNeedsSnacks** [comment]
Version [2.0.0](https://www.curseforge.com/minecraft/mc-mods/interactio/files/2901798) that added this feature just got approved on CurseForge, have fun! \o/
