### ISSUE TITLE
nbt tags ignored when used for inputs

### ISSUE THREAD

**Issue by dozingpip** [MaxNeedsSnacks/Interactio#52]
my version info: Minecraft 1.16.5, Forge 36.0.43, Interactio version 3.1.1

[See example here](https://pastebin.com/n44CDr4e).
The water bottle shows up in JEI as an uncraftable potion, and the efficiency 1 book shows up as an enchanted book with no specific enchantments. The nbt tags on the outputs seem to work fine in JEI though.
![2021-05-10_01 08 54](https://user-images.githubusercontent.com/6119565/117608609-6bc9d980-b12c-11eb-97ba-d048c5daaf77.png)
To be clear, the recipe does work as intended, it just doesn't show up correctly in JEI.
Thanks!

**Comment by dozingpip** [comment]
Nevermind, it just accepts any potion/ enchanted book as input for the recipe, so not just JEI here.

**Comment by dozingpip** [comment]
Sorry, I found #38 but I think that fix should be in the documentation somewhere? I know the wiki still kind of a wip right now though...
Thanks!

**Comment by MaxNeedsSnacks** [comment]
I added an example case for Forge ingredients to the wiki (though *they* should really document this better for non-modders as well)
