### ISSUE TITLE
Log spam when player joins server

### ISSUE THREAD

**Issue by Wxrlds** [MaxNeedsSnacks/Interactio#53]
Title says it all. When a player joins a server it throws this message in the console
``[Netty Epoll Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize dev.maxneedssnacks.interactio.command.RegistryArgument@73f78e37 (class dev.maxneedssnacks.interactio.command.RegistryArgument) - will not be sent to client!
``
Possibly related to https://github.com/MaxNeedsSnacks/Interactio/issues/32
Modpack used: [Spirited Dynamics](https://www.curseforge.com/minecraft/modpacks/spirited-dynamics/files/3318100)

**Comment by MaxNeedsSnacks** [comment]
This has been fixed in dev quite some time ago, but I haven't had time to clean up the new release yet, unfortunately :/
