### ISSUE TITLE
Still not getting the recipe to do anything, nor errors.

### ISSUE THREAD

**Issue by Boolyman** [MaxNeedsSnacks/Interactio#59]
You closed the other ticket so I don't know if I need to fill out a new one to keep corresponding.

I have removed the "item:" syntax.  And removed the incorrect "__oil" from the fluid ID. I have quadruple checked all the IDs, and compared this syntax to the syntax used in another pack.

There is a message on the mod download page stating that if you are on 1.15 MixinBootstrap is required. Does that apply to 1.16.5 as well? I have tried it with and without that as a dependency, and it still doesnt work.

I have also checked the log and there is no mention of any errors with interactio.

This is the exact syntax I am now using:

{
"type": "interactio:fluid_fluid_transform",
"items": [
{
"item": "rustic_resources:charcoalclump",
"count": 1,
}
],
"input": {
"fluid": "water"
},
"output": {
"fluid": "immersiveengineering:creosote"
}
}

**Comment by MaxNeedsSnacks** [comment]
What mod is the Charcoal Clump from? The ID says "Rustic Resources", but I don't know that mod. If it's from Rustic, should it maybe just be rustic:*?

**Comment by Boolyman** [comment]
Thats a custom mod for my upcoming pack, it hasnt been released yet.  

I just now created a blank pack, with the only mods installed being: Kubejs, JEI, Immersive Engineering, and Interactio.  Transported my script over, AND replaced the `"rustic_resources:charcoalclump"` with `"minecraft:coal"` and it still doesnt work.

Could it be something with my folder structure?
`kubejs/data/inworldcrafting/recipes/water_to_creosote.json`

All I need to do is throw a piece of coal into a source block of water and it should work, right?

This is the exact syntax of my file in this new blank pack:

{
  "type": "interactio:fluid_fluid_transform",
  "items": [
    {
      "item": "minecraft:coal",
      "count": 1,
    }
  ],
  "input": {
    "fluid": "water"
  },
  "output": {
              "fluid": "immersiveengineering:creosote"
        }
}

**Comment by Boolyman** [comment]
I have also tried it with thermal's creosote oil... "thermal:creosote" to no avail

**Comment by MaxNeedsSnacks** [comment]
Oh wait, you're using JSON recipes?

In that case this line will error due to the extra comma

```jsonc
{
"item": "minecraft:coal",
"count": 1, // << HERE
}
```

and you **should** have gotten an error in console

**Comment by Boolyman** [comment]
There we go, that worked.  Thank you.
