### ISSUE TITLE
Item fluid recipes not loading

### ISSUE THREAD

**Issue by sug0** [MaxNeedsSnacks/Interactio#6]
Unless I do a `/reload`, the item fluid recipes don't work on 1.14.4, with `Interactio-1.15.2-1.3.1.jar`. I was testing the glass bottle example from the wiki. I'm also using the global datapacks mod, but I don't think that's the problem.

**Comment by MaxNeedsSnacks** [comment]
Heya, does anything get printed in the console by any chance? Everything *should* be working fine on my end, so this is a bit worrying.

**Comment by MaxNeedsSnacks** [comment]
Able to confirm this in userdev, unfortunately... lemme see what's wrong, hm...

**Comment by MaxNeedsSnacks** [comment]
Looks like this issue isn't specific to 1.14, either, i just messed up something with client/server sidedness... again. gdi

new release on curseforge should hopefully fix this, let me know if it did ^^

**Comment by MaxNeedsSnacks** [comment]
okay, curseforge is taking a long time to actually approve the 1.14 release, i'm gonna start a manual build so you can test it out ingame.

**Comment by sug0** [comment]
thanks dude!

**Comment by MaxNeedsSnacks** [comment]
No worries, lemme know if you need anything else or if this version borked something else (hopefully not tho lol)

**Comment by sug0** [comment]
I'll test it now, see if I spot anything else. Great mod, btw. I'm using it on a vanilla-ish pack I built for myself, where ore duplication is done with the tnt explosions. :P

**Comment by sug0** [comment]
Looks like everything is in order. For me the issue is closeable.

**Comment by MaxNeedsSnacks** [comment]
Great, thanks for reporting this again, idk how I didn't spot this ^^
