### ISSUE TITLE
not possible to craft with flowing water

### ISSUE THREAD

**Issue by Kr8vzn** [MaxNeedsSnacks/Interactio#61]
if I use item_fluid_transform to make recipe with "water" it works but when I switch to "flowing_water" it does not work.
Is there any way to use flowing water?
I have tried "minecraft:flowing_water" and fluid tag "water"

**Comment by MaxNeedsSnacks** [comment]
If you use a recipe with water that *doesn't* consume the fluid, just using "water" will also accept flowing water, however, if the fluid is consumed, I figured it would have been too cheaty to allow for people to use the flowing variant (since that automatically refills), so that's by design

**Comment by Kr8vzn** [comment]
With the 3.1.1 version of the mod this behaviour will not happen as the fluid will never pass the commented out line if not a source, just need to remove ``` || !state.isSource()``` as shown
```
    public boolean canCraft(List<ItemEntity> entities, FluidState state) {
        // if (!fluid.test(state.getFluid()) || !state.isSource()) return false;
        if (!fluid.test(state.getFluid())) return false;
        if (consumeFluid > 0 && !state.isSource()) return false;

        return compareStacks(entities, inputs);
    }
```
after this, i still need to explicitly put "flowing_water" in recipe for it to work, just "water" did not work
